on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

name: Tests

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
        pyversion: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Run pytest
      shell: bash
      run: uv run --python ${{ matrix.pyversion }} --locked pytest
